package com.awesomeapp.profile.di

import dagger.Module
import dagger.Provides
import dagger.hilt.InstallIn
import dagger.hilt.components.SingletonComponent
import javax.inject.Singleton
import com.awesomeapp.profile.Viewmodel8_1
import com.awesomeapp.profile.Activity8_2
import com.awesomeapp.profile.Activity8_3
import com.awesomeapp.profile.Fragment8_4
import com.awesomeapp.profile.Repository8_5
import com.awesomeapp.profile.Api8_6
import com.awesomeapp.profile.Model8_8
import com.awesomeapp.profile.Model8_9
import com.awesomeapp.profile.Activity8_10
import com.awesomeapp.profile.Model8_12
import com.awesomeapp.profile.Activity8_13
import com.awesomeapp.profile.Model8_15
import com.awesomeapp.profile.Activity8_16
import com.awesomeapp.profile.Model8_18
import com.awesomeapp.profile.Activity8_19
import com.awesomeapp.profile.Model8_21
import com.awesomeapp.profile.Activity8_22
import com.awesomeapp.profile.Model8_24
import com.awesomeapp.profile.Activity8_25
import com.awesomeapp.profile.Model8_27
import com.awesomeapp.profile.Activity8_28
import com.awesomeapp.profile.Model8_30
import com.awesomeapp.profile.Activity8_31
import com.awesomeapp.profile.Model8_33
import com.awesomeapp.profile.Activity8_34
import com.awesomeapp.profile.Model8_36
import com.awesomeapp.profile.Activity8_37
import com.awesomeapp.profile.Model8_39
import com.awesomeapp.profile.Activity8_40
import com.awesomeapp.profile.Model8_42
import com.awesomeapp.profile.Activity8_43
import com.awesomeapp.profile.Model8_45
import com.awesomeapp.profile.Activity8_46
import com.awesomeapp.profile.Model8_48
import com.awesomeapp.profile.Activity8_49
import com.awesomeapp.profile.Model8_51
import com.awesomeapp.profile.Activity8_52
import com.awesomeapp.profile.Model8_54
import com.awesomeapp.profile.Activity8_55
import com.awesomeapp.profile.Model8_57
import com.awesomeapp.profile.Activity8_58
import com.awesomeapp.profile.Model8_60
import com.awesomeapp.profile.Activity8_61
import com.awesomeapp.profile.Model8_63
import com.awesomeapp.profile.Activity8_64
import com.awesomeapp.profile.Model8_66
import com.awesomeapp.profile.Activity8_67
import com.awesomeapp.profile.Model8_69
import com.awesomeapp.profile.Activity8_70
import com.awesomeapp.profile.Model8_72
import com.awesomeapp.profile.Activity8_73
import com.awesomeapp.profile.Model8_75
import com.awesomeapp.profile.Activity8_76
import com.awesomeapp.profile.Model8_78
import com.awesomeapp.profile.Activity8_79
import com.awesomeapp.profile.Model8_81
import com.awesomeapp.profile.Activity8_82
import com.awesomeapp.profile.Model8_84
import com.awesomeapp.profile.Activity8_85
import com.awesomeapp.profile.Model8_87
import com.awesomeapp.profile.Activity8_88
import com.awesomeapp.profile.Model8_90
import com.awesomeapp.profile.Activity8_91
import com.awesomeapp.profile.Model8_93
import com.awesomeapp.profile.Activity8_94
import com.awesomeapp.profile.Model8_96
import com.awesomeapp.profile.Activity8_97
import com.awesomeapp.profile.Model8_99
import com.awesomeapp.profile.Activity8_100
import com.awesomeapp.profile.Model8_102
import com.awesomeapp.profile.Activity8_103
import com.awesomeapp.profile.Model8_105
import com.awesomeapp.profile.Activity8_106
import com.awesomeapp.profile.Model8_108
import com.awesomeapp.profile.Activity8_109
import com.awesomeapp.profile.Model8_111
import com.awesomeapp.profile.Activity8_112
import com.awesomeapp.profile.Model8_114
import com.awesomeapp.profile.Activity8_115
import com.awesomeapp.profile.Model8_117
import com.awesomeapp.profile.Activity8_118
import com.awesomeapp.profile.Model8_120
import com.awesomeapp.profile.Activity8_121
import com.awesomeapp.profile.Model8_123
import com.awesomeapp.profile.Activity8_124
import com.awesomeapp.profile.Model8_126
import com.awesomeapp.profile.Activity8_127
import com.awesomeapp.profile.Model8_129
import com.awesomeapp.profile.Activity8_130
import com.awesomeapp.profile.Model8_132
import com.awesomeapp.profile.Activity8_133
import com.awesomeapp.profile.Model8_135
import com.awesomeapp.profile.Activity8_136
import com.awesomeapp.profile.Model8_138
import com.awesomeapp.profile.Activity8_139
import com.awesomeapp.profile.Model8_141
import com.awesomeapp.profile.Activity8_142
import com.awesomeapp.profile.Model8_144
import com.awesomeapp.profile.Activity8_145
import com.awesomeapp.profile.Model8_147
import com.awesomeapp.profile.Activity8_148
import com.awesomeapp.profile.Model8_150
import com.awesomeapp.profile.Activity8_151
import com.awesomeapp.profile.Model8_153
import com.awesomeapp.profile.Activity8_154
import com.awesomeapp.profile.Model8_156
import com.awesomeapp.profile.Activity8_157
import com.awesomeapp.profile.Model8_159
import com.awesomeapp.profile.Activity8_160
import com.awesomeapp.profile.Model8_162
import com.awesomeapp.profile.Activity8_163
import com.awesomeapp.profile.Model8_165
import com.awesomeapp.profile.Activity8_166
import com.awesomeapp.profile.Model8_168
import com.awesomeapp.profile.Activity8_169
import com.awesomeapp.profile.Model8_171
import com.awesomeapp.profile.Activity8_172
import com.awesomeapp.profile.Model8_174
import com.awesomeapp.profile.Activity8_175
import com.awesomeapp.profile.Model8_177
import com.awesomeapp.profile.Activity8_178
import com.awesomeapp.profile.Model8_180
import com.awesomeapp.profile.Activity8_181
import com.awesomeapp.profile.Model8_183
import com.awesomeapp.profile.Activity8_184
import com.awesomeapp.profile.Model8_186
import com.awesomeapp.profile.Activity8_187
import com.awesomeapp.profile.Model8_189
import com.awesomeapp.profile.Activity8_190
import com.awesomeapp.profile.Model8_192
import com.awesomeapp.profile.Activity8_193
import com.awesomeapp.profile.Model8_195
import com.awesomeapp.profile.Activity8_196
import com.awesomeapp.profile.Model8_198
import com.awesomeapp.profile.Activity8_199
import com.awesomeapp.profile.Model8_201
import com.awesomeapp.profile.Activity8_202
import com.awesomeapp.profile.Model8_204
import com.awesomeapp.profile.Activity8_205
import com.awesomeapp.profile.Model8_207
import com.awesomeapp.profile.Activity8_208
import com.awesomeapp.profile.Model8_210
import com.awesomeapp.profile.Activity8_211
import com.awesomeapp.profile.Model8_213
import com.awesomeapp.profile.Activity8_214
import com.awesomeapp.profile.Model8_216
import com.awesomeapp.profile.Activity8_217
import com.awesomeapp.profile.Model8_219
import com.awesomeapp.profile.Activity8_220
import com.awesomeapp.profile.Model8_222
import com.awesomeapp.profile.Activity8_223
import com.awesomeapp.profile.Model8_225
import com.awesomeapp.profile.Activity8_226
import com.awesomeapp.profile.Model8_228
import com.awesomeapp.profile.Activity8_229
import com.awesomeapp.profile.Model8_231
import com.awesomeapp.profile.Activity8_232
import com.awesomeapp.profile.Model8_234
import com.awesomeapp.profile.Activity8_235
import com.awesomeapp.profile.Model8_237
import com.awesomeapp.profile.Activity8_238
import com.awesomeapp.profile.Model8_240
import com.awesomeapp.profile.Activity8_241
import com.awesomeapp.profile.Model8_243
import com.awesomeapp.profile.Activity8_244
import com.awesomeapp.profile.Model8_246
import com.awesomeapp.profile.Activity8_247
import com.awesomeapp.profile.Model8_249
import com.awesomeapp.profile.Activity8_250
import com.awesomeapp.profile.Model8_252
import com.awesomeapp.profile.Activity8_253
import com.awesomeapp.profile.Model8_255
import com.awesomeapp.profile.Activity8_256
import com.awesomeapp.profile.Model8_258
import com.awesomeapp.profile.Activity8_259
import com.awesomeapp.profile.Model8_261
import com.awesomeapp.profile.Activity8_262
import com.awesomeapp.profile.Model8_264
import com.awesomeapp.profile.Activity8_265
import com.awesomeapp.profile.Model8_267
import com.awesomeapp.profile.Activity8_268
import com.awesomeapp.profile.Model8_270
import com.awesomeapp.profile.Activity8_271
import com.awesomeapp.profile.Model8_273
import com.awesomeapp.profile.Activity8_274
import com.awesomeapp.profile.Model8_276
import com.awesomeapp.profile.Activity8_277
import com.awesomeapp.profile.Model8_279
import com.awesomeapp.profile.Activity8_280
import com.awesomeapp.profile.Model8_282
import com.awesomeapp.profile.Activity8_283
import com.awesomeapp.profile.Model8_285
import com.awesomeapp.profile.Activity8_286
import com.awesomeapp.profile.Model8_288
import com.awesomeapp.profile.Activity8_289
import com.awesomeapp.profile.Model8_291
import com.awesomeapp.profile.Activity8_292
import com.awesomeapp.profile.Model8_294
import com.awesomeapp.profile.Activity8_295
import com.awesomeapp.profile.Model8_297
import com.awesomeapp.profile.Activity8_298
import com.awesomeapp.profile.Model8_300
import com.awesomeapp.profile.Activity8_301
import com.awesomeapp.profile.Model8_303
import com.awesomeapp.profile.Activity8_304
import com.awesomeapp.profile.Model8_306
import com.awesomeapp.profile.Activity8_307
import com.awesomeapp.profile.Model8_309
import com.awesomeapp.profile.Activity8_310
import com.awesomeapp.profile.Model8_312
import com.awesomeapp.profile.Activity8_313
import com.awesomeapp.profile.Model8_315
import com.awesomeapp.profile.Activity8_316
import com.awesomeapp.profile.Model8_318
import com.awesomeapp.profile.Activity8_319
import com.awesomeapp.profile.Model8_321
import com.awesomeapp.profile.Activity8_322
import com.awesomeapp.profile.Model8_324
import com.awesomeapp.profile.Activity8_325
import com.awesomeapp.profile.Model8_327
import com.awesomeapp.profile.Activity8_328
import com.awesomeapp.profile.Model8_330
import com.awesomeapp.profile.Activity8_331
import com.awesomeapp.profile.Model8_333
import com.awesomeapp.profile.Activity8_334
import com.awesomeapp.profile.Model8_336
import com.awesomeapp.profile.Activity8_337
import com.awesomeapp.profile.Model8_339
import com.awesomeapp.profile.Activity8_340
import com.awesomeapp.profile.Model8_342
import com.awesomeapp.profile.Activity8_343
import com.awesomeapp.profile.Model8_345
import com.awesomeapp.profile.Activity8_346
import com.awesomeapp.profile.Model8_348
import com.awesomeapp.profile.Activity8_349
import com.awesomeapp.profile.Model8_351
import com.awesomeapp.profile.Activity8_352
import com.awesomeapp.profile.Model8_354
import com.awesomeapp.profile.Activity8_355
import com.awesomeapp.profile.Model8_357
import com.awesomeapp.profile.Activity8_358
import com.awesomeapp.profile.Model8_360
import com.awesomeapp.profile.Activity8_361
import com.awesomeapp.profile.Model8_363
import com.awesomeapp.profile.Activity8_364
import com.awesomeapp.profile.Model8_366
import com.awesomeapp.profile.Activity8_367
import com.awesomeapp.profile.Model8_369
import com.awesomeapp.profile.Activity8_370
import com.awesomeapp.profile.Model8_372
import com.awesomeapp.profile.Activity8_373
import com.awesomeapp.profile.Model8_375
import com.awesomeapp.profile.Activity8_376
import com.awesomeapp.profile.Model8_378
import com.awesomeapp.profile.Activity8_379
import com.awesomeapp.profile.Model8_381
import com.awesomeapp.profile.Activity8_382
import com.awesomeapp.profile.Model8_384
import com.awesomeapp.profile.Activity8_385
import com.awesomeapp.profile.Model8_387
import com.awesomeapp.profile.Activity8_388
import com.awesomeapp.profile.Model8_390
import com.awesomeapp.profile.Activity8_391
import com.awesomeapp.profile.Model8_393
import com.awesomeapp.profile.Activity8_394
import com.awesomeapp.profile.Model8_396
import com.awesomeapp.profile.Activity8_397
import com.awesomeapp.profile.Model8_399
import com.awesomeapp.profile.Activity8_400
import com.awesomeapp.profile.Model8_402
import com.awesomeapp.profile.Activity8_403
import com.awesomeapp.profile.Model8_405
import com.awesomeapp.profile.Activity8_406
import com.awesomeapp.profile.Model8_408
import com.awesomeapp.profile.Activity8_409
import com.awesomeapp.profile.Model8_411
import com.awesomeapp.profile.Activity8_412
import com.awesomeapp.profile.Model8_414
import com.awesomeapp.profile.Activity8_415
import com.awesomeapp.profile.Model8_417
import com.awesomeapp.profile.Activity8_418
import com.awesomeapp.profile.Model8_420
import com.awesomeapp.profile.Activity8_421
import com.awesomeapp.profile.Model8_423
import com.awesomeapp.profile.Activity8_424
import com.awesomeapp.profile.Model8_426
import com.awesomeapp.profile.Activity8_427
import com.awesomeapp.profile.Model8_429
import com.awesomeapp.profile.Activity8_430
import com.awesomeapp.profile.Model8_432
import com.awesomeapp.profile.Activity8_433
import com.awesomeapp.profile.Model8_435
import com.awesomeapp.profile.Activity8_436
import com.awesomeapp.profile.Model8_438
import com.awesomeapp.profile.Activity8_439
import com.awesomeapp.profile.Model8_441
import com.awesomeapp.profile.Activity8_442
import com.awesomeapp.profile.Model8_444
import com.awesomeapp.profile.Activity8_445
import com.awesomeapp.profile.Model8_447
import com.awesomeapp.profile.Activity8_448
import com.awesomeapp.profile.Model8_450
import com.awesomeapp.profile.Activity8_451
import com.awesomeapp.profile.Model8_453
import com.awesomeapp.profile.Activity8_454
import com.awesomeapp.profile.Model8_456
import com.awesomeapp.profile.Activity8_457
import com.awesomeapp.profile.Model8_459
import com.awesomeapp.profile.Activity8_460
import com.awesomeapp.profile.Model8_462

@Module
@InstallIn(SingletonComponent::class)
object Module_8 {
    @Provides
    @Singleton
    fun provideRepository8_5(): Repository8_5 {
        return Repository8_5()
    }

    @Provides
    @Singleton
    fun provideApi8_6(): Api8_6 {
        return Api8_6()
    }
}