package com.awesomeapp.identity.di

import dagger.Module
import dagger.Provides
import dagger.hilt.InstallIn
import dagger.hilt.components.SingletonComponent
import javax.inject.Singleton
import com.awesomeapp.identity.Viewmodel4_1
import com.awesomeapp.identity.Activity4_2
import com.awesomeapp.identity.Activity4_3
import com.awesomeapp.identity.Fragment4_4
import com.awesomeapp.identity.Repository4_5
import com.awesomeapp.identity.Api4_6
import com.awesomeapp.identity.Model4_8
import com.awesomeapp.identity.Model4_9
import com.awesomeapp.identity.Activity4_10
import com.awesomeapp.identity.Model4_12
import com.awesomeapp.identity.Activity4_13
import com.awesomeapp.identity.Model4_15
import com.awesomeapp.identity.Activity4_16
import com.awesomeapp.identity.Model4_18
import com.awesomeapp.identity.Activity4_19
import com.awesomeapp.identity.Model4_21
import com.awesomeapp.identity.Activity4_22
import com.awesomeapp.identity.Model4_24
import com.awesomeapp.identity.Activity4_25
import com.awesomeapp.identity.Model4_27
import com.awesomeapp.identity.Activity4_28
import com.awesomeapp.identity.Model4_30
import com.awesomeapp.identity.Activity4_31
import com.awesomeapp.identity.Model4_33
import com.awesomeapp.identity.Activity4_34
import com.awesomeapp.identity.Model4_36
import com.awesomeapp.identity.Activity4_37
import com.awesomeapp.identity.Model4_39
import com.awesomeapp.identity.Activity4_40
import com.awesomeapp.identity.Model4_42
import com.awesomeapp.identity.Activity4_43
import com.awesomeapp.identity.Model4_45
import com.awesomeapp.identity.Activity4_46
import com.awesomeapp.identity.Model4_48
import com.awesomeapp.identity.Activity4_49
import com.awesomeapp.identity.Model4_51
import com.awesomeapp.identity.Activity4_52
import com.awesomeapp.identity.Model4_54
import com.awesomeapp.identity.Activity4_55
import com.awesomeapp.identity.Model4_57
import com.awesomeapp.identity.Activity4_58
import com.awesomeapp.identity.Model4_60
import com.awesomeapp.identity.Activity4_61
import com.awesomeapp.identity.Model4_63
import com.awesomeapp.identity.Activity4_64
import com.awesomeapp.identity.Model4_66
import com.awesomeapp.identity.Activity4_67
import com.awesomeapp.identity.Model4_69
import com.awesomeapp.identity.Activity4_70
import com.awesomeapp.identity.Model4_72
import com.awesomeapp.identity.Activity4_73
import com.awesomeapp.identity.Model4_75
import com.awesomeapp.identity.Activity4_76
import com.awesomeapp.identity.Model4_78
import com.awesomeapp.identity.Activity4_79
import com.awesomeapp.identity.Model4_81
import com.awesomeapp.identity.Activity4_82
import com.awesomeapp.identity.Model4_84
import com.awesomeapp.identity.Activity4_85
import com.awesomeapp.identity.Model4_87
import com.awesomeapp.identity.Activity4_88
import com.awesomeapp.identity.Model4_90
import com.awesomeapp.identity.Activity4_91
import com.awesomeapp.identity.Model4_93
import com.awesomeapp.identity.Activity4_94
import com.awesomeapp.identity.Model4_96
import com.awesomeapp.identity.Activity4_97
import com.awesomeapp.identity.Model4_99
import com.awesomeapp.identity.Activity4_100
import com.awesomeapp.identity.Model4_102
import com.awesomeapp.identity.Activity4_103
import com.awesomeapp.identity.Model4_105
import com.awesomeapp.identity.Activity4_106
import com.awesomeapp.identity.Model4_108
import com.awesomeapp.identity.Activity4_109
import com.awesomeapp.identity.Model4_111
import com.awesomeapp.identity.Activity4_112
import com.awesomeapp.identity.Model4_114
import com.awesomeapp.identity.Activity4_115
import com.awesomeapp.identity.Model4_117
import com.awesomeapp.identity.Activity4_118
import com.awesomeapp.identity.Model4_120
import com.awesomeapp.identity.Activity4_121
import com.awesomeapp.identity.Model4_123
import com.awesomeapp.identity.Activity4_124
import com.awesomeapp.identity.Model4_126
import com.awesomeapp.identity.Activity4_127
import com.awesomeapp.identity.Model4_129
import com.awesomeapp.identity.Activity4_130
import com.awesomeapp.identity.Model4_132
import com.awesomeapp.identity.Activity4_133
import com.awesomeapp.identity.Model4_135
import com.awesomeapp.identity.Activity4_136
import com.awesomeapp.identity.Model4_138
import com.awesomeapp.identity.Activity4_139
import com.awesomeapp.identity.Model4_141
import com.awesomeapp.identity.Activity4_142
import com.awesomeapp.identity.Model4_144
import com.awesomeapp.identity.Activity4_145
import com.awesomeapp.identity.Model4_147
import com.awesomeapp.identity.Activity4_148
import com.awesomeapp.identity.Model4_150
import com.awesomeapp.identity.Activity4_151
import com.awesomeapp.identity.Model4_153
import com.awesomeapp.identity.Activity4_154
import com.awesomeapp.identity.Model4_156
import com.awesomeapp.identity.Activity4_157
import com.awesomeapp.identity.Model4_159
import com.awesomeapp.identity.Activity4_160
import com.awesomeapp.identity.Model4_162
import com.awesomeapp.identity.Activity4_163
import com.awesomeapp.identity.Model4_165
import com.awesomeapp.identity.Activity4_166
import com.awesomeapp.identity.Model4_168
import com.awesomeapp.identity.Activity4_169
import com.awesomeapp.identity.Model4_171
import com.awesomeapp.identity.Activity4_172
import com.awesomeapp.identity.Model4_174
import com.awesomeapp.identity.Activity4_175
import com.awesomeapp.identity.Model4_177
import com.awesomeapp.identity.Activity4_178
import com.awesomeapp.identity.Model4_180
import com.awesomeapp.identity.Activity4_181
import com.awesomeapp.identity.Model4_183
import com.awesomeapp.identity.Activity4_184
import com.awesomeapp.identity.Model4_186
import com.awesomeapp.identity.Activity4_187
import com.awesomeapp.identity.Model4_189
import com.awesomeapp.identity.Activity4_190
import com.awesomeapp.identity.Model4_192
import com.awesomeapp.identity.Activity4_193
import com.awesomeapp.identity.Model4_195
import com.awesomeapp.identity.Activity4_196
import com.awesomeapp.identity.Model4_198
import com.awesomeapp.identity.Activity4_199
import com.awesomeapp.identity.Model4_201
import com.awesomeapp.identity.Activity4_202
import com.awesomeapp.identity.Model4_204
import com.awesomeapp.identity.Activity4_205
import com.awesomeapp.identity.Model4_207
import com.awesomeapp.identity.Activity4_208
import com.awesomeapp.identity.Model4_210
import com.awesomeapp.identity.Activity4_211
import com.awesomeapp.identity.Model4_213
import com.awesomeapp.identity.Activity4_214
import com.awesomeapp.identity.Model4_216
import com.awesomeapp.identity.Activity4_217
import com.awesomeapp.identity.Model4_219
import com.awesomeapp.identity.Activity4_220
import com.awesomeapp.identity.Model4_222
import com.awesomeapp.identity.Activity4_223
import com.awesomeapp.identity.Model4_225
import com.awesomeapp.identity.Activity4_226
import com.awesomeapp.identity.Model4_228
import com.awesomeapp.identity.Activity4_229
import com.awesomeapp.identity.Model4_231
import com.awesomeapp.identity.Activity4_232
import com.awesomeapp.identity.Model4_234
import com.awesomeapp.identity.Activity4_235
import com.awesomeapp.identity.Model4_237
import com.awesomeapp.identity.Activity4_238
import com.awesomeapp.identity.Model4_240
import com.awesomeapp.identity.Activity4_241
import com.awesomeapp.identity.Model4_243
import com.awesomeapp.identity.Activity4_244
import com.awesomeapp.identity.Model4_246
import com.awesomeapp.identity.Activity4_247
import com.awesomeapp.identity.Model4_249
import com.awesomeapp.identity.Activity4_250
import com.awesomeapp.identity.Model4_252
import com.awesomeapp.identity.Activity4_253
import com.awesomeapp.identity.Model4_255
import com.awesomeapp.identity.Activity4_256
import com.awesomeapp.identity.Model4_258
import com.awesomeapp.identity.Activity4_259
import com.awesomeapp.identity.Model4_261
import com.awesomeapp.identity.Activity4_262
import com.awesomeapp.identity.Model4_264
import com.awesomeapp.identity.Activity4_265
import com.awesomeapp.identity.Model4_267
import com.awesomeapp.identity.Activity4_268
import com.awesomeapp.identity.Model4_270
import com.awesomeapp.identity.Activity4_271
import com.awesomeapp.identity.Model4_273
import com.awesomeapp.identity.Activity4_274
import com.awesomeapp.identity.Model4_276
import com.awesomeapp.identity.Activity4_277
import com.awesomeapp.identity.Model4_279
import com.awesomeapp.identity.Activity4_280
import com.awesomeapp.identity.Model4_282
import com.awesomeapp.identity.Activity4_283
import com.awesomeapp.identity.Model4_285
import com.awesomeapp.identity.Activity4_286
import com.awesomeapp.identity.Model4_288
import com.awesomeapp.identity.Activity4_289
import com.awesomeapp.identity.Model4_291
import com.awesomeapp.identity.Activity4_292
import com.awesomeapp.identity.Model4_294
import com.awesomeapp.identity.Activity4_295
import com.awesomeapp.identity.Model4_297
import com.awesomeapp.identity.Activity4_298
import com.awesomeapp.identity.Model4_300
import com.awesomeapp.identity.Activity4_301
import com.awesomeapp.identity.Model4_303
import com.awesomeapp.identity.Activity4_304
import com.awesomeapp.identity.Model4_306
import com.awesomeapp.identity.Activity4_307
import com.awesomeapp.identity.Model4_309
import com.awesomeapp.identity.Activity4_310
import com.awesomeapp.identity.Model4_312
import com.awesomeapp.identity.Activity4_313
import com.awesomeapp.identity.Model4_315
import com.awesomeapp.identity.Activity4_316
import com.awesomeapp.identity.Model4_318
import com.awesomeapp.identity.Activity4_319
import com.awesomeapp.identity.Model4_321
import com.awesomeapp.identity.Activity4_322
import com.awesomeapp.identity.Model4_324
import com.awesomeapp.identity.Activity4_325
import com.awesomeapp.identity.Model4_327
import com.awesomeapp.identity.Activity4_328
import com.awesomeapp.identity.Model4_330
import com.awesomeapp.identity.Activity4_331
import com.awesomeapp.identity.Model4_333
import com.awesomeapp.identity.Activity4_334
import com.awesomeapp.identity.Model4_336
import com.awesomeapp.identity.Activity4_337
import com.awesomeapp.identity.Model4_339
import com.awesomeapp.identity.Activity4_340
import com.awesomeapp.identity.Model4_342
import com.awesomeapp.identity.Activity4_343
import com.awesomeapp.identity.Model4_345
import com.awesomeapp.identity.Activity4_346
import com.awesomeapp.identity.Model4_348
import com.awesomeapp.identity.Activity4_349
import com.awesomeapp.identity.Model4_351
import com.awesomeapp.identity.Activity4_352
import com.awesomeapp.identity.Model4_354
import com.awesomeapp.identity.Activity4_355
import com.awesomeapp.identity.Model4_357
import com.awesomeapp.identity.Activity4_358
import com.awesomeapp.identity.Model4_360
import com.awesomeapp.identity.Activity4_361
import com.awesomeapp.identity.Model4_363
import com.awesomeapp.identity.Activity4_364
import com.awesomeapp.identity.Model4_366
import com.awesomeapp.identity.Activity4_367
import com.awesomeapp.identity.Model4_369
import com.awesomeapp.identity.Activity4_370
import com.awesomeapp.identity.Model4_372

@Module
@InstallIn(SingletonComponent::class)
object Module_4 {
    @Provides
    @Singleton
    fun provideRepository4_5(): Repository4_5 {
        return Repository4_5()
    }

    @Provides
    @Singleton
    fun provideApi4_6(): Api4_6 {
        return Api4_6()
    }
}